/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDetailDrawer: typeof import('./components/alerts/AlertDetailDrawer.vue')['default']
    AlertFilters: typeof import('./components/alerts/AlertFilters.vue')['default']
    AlertTable: typeof import('./components/alerts/AlertTable.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ChartCard: typeof import('./components/analysis/ChartCard.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    EmptyState: typeof import('./components/shared/EmptyState.vue')['default']
    EvidenceTable: typeof import('./components/evidence/EvidenceTable.vue')['default']
    EvidenceTimeline: typeof import('./components/evidence/EvidenceTimeline.vue')['default']
    FlightStatus: typeof import('./components/monitoring/FlightStatus.vue')['default']
    GisMap: typeof import('./components/monitoring/GisMap.vue')['default']
    HeatmapPlaceholder: typeof import('./components/analysis/HeatmapPlaceholder.vue')['default']
    PatrolStatsCards: typeof import('./components/patrol/PatrolStatsCards.vue')['default']
    PatrolTable: typeof import('./components/patrol/PatrolTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemConfigForm: typeof import('./components/settings/SystemConfigForm.vue')['default']
    TrendChart: typeof import('./components/analysis/TrendChart.vue')['default']
    UserTable: typeof import('./components/settings/UserTable.vue')['default']
    VideoFeed: typeof import('./components/monitoring/VideoFeed.vue')['default']
    ViolationTypeChart: typeof import('./components/analysis/ViolationTypeChart.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
